### ISSUE TITLE
WTP 100 move sound is played globally forever

### ISSUE THREAD

**Issue by michaeldgg2** [notsure8x/e2140-unofficial-patch#1] opened 2023-12-05 19:20 UTC
The move sound of WTP 100 in Windows version has a bug: it loops infinitely.

## Details
- when WTP 100 is produced, its move sound is played in an infinite loop globally (without regard to WTP 100 position)
- when WTP 100 starts to move, its move sound is played locally at WTP 100 position as it should. However, the sound is now played twice.
- when WTP 100 stops moving, the locally played sound is stopped as it should (the globally played sound continues to be looped)
- when WTP 100 is killed, the globally played sound is still being looped
- the sound is played even when game is paused (like in the save/load dialog)

## Save/load behavior

- when game is saved and loaded *after* the WTP 100 is killed, the glitched loop of the move sound is gone
- when game is saved and loaded *while* the WTP 100 *is still alive*, the glitched loop of the move sound is gone. **However** the moment the WTP 100 moves, the glitched infinitely looped sound is back

## Videos reproducing the bug
Here are two videos comparing original DOS version and Windows version:

Windows version:
https://github.com/notsure8x/e2140-unofficial-patch/assets/119738087/35d851d8-2c31-47fe-b834-5c4be8cbba44

DOS version:
https://github.com/notsure8x/e2140-unofficial-patch/assets/119738087/afea52d7-feb3-4da8-ab2a-b3887fae0eeb

## Other affected units

Some other units, that make sound while moving, are also affected such as helicopters and Heavy Lifter.

**Comment by notsure8x** [comment] 2024-01-12 17:35
Root cause found, will be fixed together with #5 in 1.1 release.

**Comment by notsure8x** [comment] 2024-01-12 22:04
Added more sound channels and priority system from DOS version. Fixed in 1.1.0.

**Closed as completed by notsure8x** 2024-01-12 22:04 UTC
Labels: bug
